services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: taskhub
      POSTGRES_PASSWORD: taskhub
      POSTGRES_DB: taskhub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:

# docker compose config # 检查语法
# docker compose up -d
# docker compose ps
# docker compose down
